### ISSUE TITLE
questions in chatper3

### ISSUE THREAD

**Issue by Sunjaies** [zombieyang/geek-nodejs#7]
以下问题希望能得到老师解答，谢谢
1.    \chapter3\4.list\node\template.js
      第十行：`(function render(template) {    
          其中template参数并未得到使用，所以直接function render()就可以了吧？
     第18~20行：
         (function (relativePath, data) {
        return createTemplate(path.dirname(templatePath) + '/' + relativePath)(data);
    })  --------这段代码作为render()的入力参数应该也是不需要的，所以直接换成()吧？

2.    chapter5中对于应用的分层解耦，感觉还不够完善。
       比如，有http和geek-rpc.js两种最基本的请求协议。在应用初始化时被加载。
       但是它和data数据源只能是一对一的关系，比如在data中如果有两个http请求的数据源，分别对 
       应不同的IP地址。那么在compile http的requestor时会设置的ip地址，那么后设置的ip地址就会 
       覆盖之前设置的ip地址。两个请求会发往同一个ip地址，造成必有一个失败。（因为两个http请 
       求都用一个http请求器，虽然数据源的config彼此独立，在request-factory.js不会互相影响，但 
       requestor的complie方法中被设定的对象如http的url和geek-rpc的schemas，easysock却会被后来的 
       设定覆盖）

**Comment by zven233777** [comment]
我也发现了这个问题

**Comment by zombieyang** [comment]
1. 这个是前面演示include功能的时候留下的参数，后来确实没用到了，可以删去，多谢提醒。

2. chapter5是比较高端的内容了，整体来说是为了演示架构。细节部分的问题不必在意。这里的解决方法可以是不在compile阶段做变量存储记录的事情，全部在request阶段做。或者非要存储的话，就做个以ip为key的缓存对象。
